-- Snowflake table initialization for Stampi
-- Run this in the Snowflake console against PUNCHI.PUBLIC
-- Database: PUNCHI   Schema: PUBLIC   Warehouse: COMPUTE_WH

USE DATABASE PUNCHI;
USE SCHEMA PUBLIC;

-- 1. Raw voice/image fragments captured throughout the day
CREATE TABLE IF NOT EXISTS RAW_EVENTS (
    ID          VARCHAR(36)   DEFAULT UUID_STRING()       NOT NULL,
    USER_ID     VARCHAR(255)  NOT NULL,
    EVENT_TYPE  VARCHAR(50)   NOT NULL,
    CONTENT     TEXT          NOT NULL,
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

-- 2. Daily journal narratives synthesized from fragments
CREATE TABLE IF NOT EXISTS DAILY_JOURNALS (
    ID             VARCHAR(36)   DEFAULT UUID_STRING()       NOT NULL,
    USER_ID        VARCHAR(255)  NOT NULL,
    JOURNAL_DATE   DATE          NOT NULL,
    NARRATIVE_TEXT  TEXT,
    AUDIO_URL      VARCHAR(500),
    IS_READY       BOOLEAN       DEFAULT FALSE               NOT NULL,
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UNIQUE (USER_ID, JOURNAL_DATE)
);

-- 3. User stamp images
CREATE TABLE IF NOT EXISTS USER_STAMPS (
    ID          VARCHAR(36)   DEFAULT UUID_STRING()       NOT NULL,
    USER_ID     VARCHAR(255)  NOT NULL,
    IMAGE_URL   TEXT          NOT NULL,
    LABEL       VARCHAR(500)  DEFAULT 'Untitled',
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL
);

-- 4. Likes on friends' journals
CREATE TABLE IF NOT EXISTS USER_LIKES (
    ID                    VARCHAR(36)   DEFAULT UUID_STRING()       NOT NULL,
    USER_ID               VARCHAR(255)  NOT NULL,
    TARGET_USER_ID        VARCHAR(255)  NOT NULL,
    TARGET_JOURNAL_DATE   DATE          NOT NULL,
    CREATED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UNIQUE (USER_ID, TARGET_USER_ID, TARGET_JOURNAL_DATE)
);

-- 5. Profile display slots (which stamps appear on profile)
CREATE TABLE IF NOT EXISTS PROFILE_SLOTS (
    ID          VARCHAR(36)   DEFAULT UUID_STRING()       NOT NULL,
    USER_ID     VARCHAR(255)  NOT NULL,
    SLOT_INDEX  INTEGER       NOT NULL,
    STAMP_ID    VARCHAR(36)   NOT NULL,
    CREATED_AT  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    UNIQUE (USER_ID, SLOT_INDEX)
);
